import type { CityDefinition } from "@/lib/catalog/types";

export const madrid: CityDefinition = {
  slug: "madrid",
  name: "Madrid",
  country: "Espana",
  tagline: "Ciudad semilla para la macro web multimodal.",
  summary:
    "Madrid permite validar un planner multimodal con bus urbano oficial, bici publica, incidencias municipales y contexto regional de carretera.",
  modes: [
    "Walk",
    "Bus EMT",
    "BiciMAD",
    "Moto sharing",
    "Taxi/VTC",
    "Park and ride",
  ],
  priorities: [
    "Responder origen, destino y hora de salida o llegada con el minimo de friccion.",
    "Cruzar rutas con incidencias urbanas y DGT para explicar riesgo real.",
    "Preparar el producto para nuevas ciudades y nuevos conectores sin rehacer la app.",
  ],
  sources: [
    {
      name: "GTFS EMT Madrid",
      category: "Transit static",
      coverage: "Bus EMT en Madrid ciudad",
      format: "GTFS ZIP",
      auth: "No visible",
      status: "ready",
      url: "https://datos.emtmadrid.es/dataset/gtfs-de-emtmadrid",
      note: "Base estatica oficial mas fiable para arrancar el planner sobre EMT.",
    },
    {
      name: "EMT MobilityLabs API",
      category: "Transit realtime",
      coverage: "Servicios dinamicos EMT y movilidad asociada",
      format: "REST API",
      auth: "Si, app identifier",
      status: "ready",
      url: "https://mobilitylabs.emtmadrid.es/",
      note: "Candidata principal para tiempos reales, alertas y enriquecimiento operativo.",
    },
    {
      name: "BiciMAD stations",
      category: "Bike sharing",
      coverage: "Estaciones de BiciMAD",
      format: "CSV / GeoJSON / KML / SHP",
      auth: "No visible",
      status: "ready",
      url: "https://datos.emtmadrid.es/dataset/estaciones-de-bicimad",
      note: "Primera capa oficial de micromovilidad para first mile y last mile.",
    },
    {
      name: "Aparcamientos EMT",
      category: "Parking",
      coverage: "Aparcamientos municipales gestionados por EMT",
      format: "CSV / GeoJSON / KML / SHP",
      auth: "No visible",
      status: "ready",
      url: "https://datos.emtmadrid.es/dataset/aparcamientos-emt",
      note: "Capa util para coche mas transporte publico y escenarios park and ride.",
    },
    {
      name: "Incidencias Ayuntamiento de Madrid",
      category: "Traffic incidents",
      coverage: "Vias publicas y M-30 de Madrid",
      format: "XML",
      auth: "No visible",
      status: "ready",
      url: "http://datos.madrid.es/egob/catalogo/202062-0-trafico-incidencias-viapublica.xml",
      note: "Mejor fuente urbana inicial para explicar afectaciones de carretera en Madrid.",
    },
    {
      name: "DGT DATEX II incidents",
      category: "Regional traffic",
      coverage: "Red estatal con impacto en accesos a Madrid",
      format: "DATEX II v3.6 XML",
      auth: "No visible",
      status: "ready",
      url: "https://nap.dgt.es/datex2/v3/dgt/SituationPublication/datex2_v36.xml",
      note: "Aporta contexto regional para entradas y salidas de Madrid.",
    },
    {
      name: "CRTM open data",
      category: "Regional transit",
      coverage: "Ecosistema de transporte regional de Madrid",
      format: "Portal open data",
      auth: "Pendiente segun dataset",
      status: "research",
      url: "https://datos.crtm.es/",
      note: "Ruta natural para ampliar a red regional, Metro y Cercanias si aparecen feeds reutilizables.",
    },
    {
      name: "Taxi, moto sharing y operadores adicionales",
      category: "Extended mobility",
      coverage: "Madrid ciudad",
      format: "APIs varias",
      auth: "Pendiente",
      status: "planned",
      url: "https://www.madrid.es/portal/site/munimadrid",
      note: "Se integran con conectores dedicados despues del MVP base.",
    },
  ],
};
